### ISSUE TITLE
Is it possible to set the Calculate Network Locations to parallel processing as well?

### ISSUE THREAD

**Issue by iamaflyingsquirrel** [Esri/large-network-analysis-tools#34]
I regularly have to process 13m+ points which get updated monthly.  It currently takes me well over a day to calculate the network locations before sending them through the OD Matrix part, and each month I have to redo them from scratch (they are new locations, so I can't reuse old values).

Is it possible to spread the Calculate Network Locations tool over multiple processes in the same way as the OD Matrix part?

That level of Python is well above my level of understanding, but any updates to the tool, or tips on how best to pre-process the data would be greatly appreciated!

@mmorang

**Comment by mmorang** [comment]
That you for this excellent suggestion.  I don't know why I never thought of it myself!

Calculating locations can, indeed, be very slow, so I think parallelizing this process makes a lot of sense.  I will have to ponder the best way to approach it since you can't write to the same geodatabase or feature class from multiple processes at the same time.  I would have to store the location fields somewhere else and rejoin them, but that can be done.

I am adding this to my to-do list.  However, I'm not sure when I can get to it, so you may have another couple of months of slow processing.  I will update this issue when I have a solution.

**Comment by iamaflyingsquirrel** [comment]
Thanks Melinda!  Much appreciated.

**Comment by mmorang** [comment]
Hello @iamaflyingsquirrel.  I spoke with the developer on my team who wrote the locating logic, and he expressed interest in learning more about your 13 million points.  I'm curious as well!  Would you be willing to tell us more about your analysis?

For the short term, parallelizing the call to Calculate Locations in this tool is definitely the way to go.  For the long term, my team is interested in improving the efficiency of the locating logic under the hood to better account for clustered points and large datasets generally.  Would it be possible for you to share an example of your 13m points with us?  (We understand if not, if it's proprietary or confidential or whatever.  You can also scrub out/delete any fields.  We're mostly interested in the geographic distribution of the points.)

Thanks.

**Comment by mmorang** [comment]
PS.  You can e-mail me privately at mmorang@esri.com if you don't want to post info for the whole world to see.

**Comment by iamaflyingsquirrel** [comment]
Thanks Melinda, will send you an email!

**Comment by mmorang** [comment]
And done!  Please pull the latest repo changes or download the latest release.  It includes a new Parallel Calculate Locations tool if you want to just calculate your locations separately up front.  Or, if you're running one of the other tools, and you tell it to precalculate network locations, it will use the parallelized logic.  Please let me know how this works for you and if you have any problems with it.  Thanks again for the great idea.  Should have done this ages ago!

**Comment by mmorang** [comment]
Apparently I forgot to close this issue.
