### ISSUE TITLE
Empty geometries in Line-FeatureClass result of SolveLargeODCostMatrix

### ISSUE THREAD

**Issue by croemer1** [Esri/large-network-analysis-tools#45]
Hi,

first, thank you for your work here!

I have a question about the featureClass Output of the SolveLargeODCostMatrix tool.
I use ArcGIS Pro 2.9.5 (Python 3.7.11) under Windows 10, 64-bit and downloaded the last version of the tools here.

The tool SolveLargeODCostMatrix runs without an error or a warning from the Toolbox in ArcGIS Pro. 
The table of the Output OD Matrix is fine, Total_Time and Total_Distance and DestinationRank is calculated correctly,
Just the LineFeatures between Origin and Destinations are missing. There are empty geometries in the line-layer output, also Shape_Length in the table is 0.
I tried a lot, different origin and destination input sources (5-some hundred , different projections of all layers (4326 and 25832), nothing worked, always empty geometries. If i use the OD cost matrix from the network analyst toolbar with the same input, everything is fine.

My settings were (I tried some changes but nothing changed my empyt geometry results):
Travel mode "Driving time", Unit "Meters", max origins "100" up to "1000", parallel processe "4", Output OD "Feature class", cutoff "", Number of Destinations "2", Time of day "", Precalulcate "Yes", Sort "Yes". 

Is this a known issue?

Regards Christoph

**Comment by mmorang** [comment]
Hi Christoph.  This is by design.  My research indicated that most users don't need the line geometry, and the OD Cost Matrix runs a little faster when it doesn't have to generate the shapes.  This is why it is set to "No Lines" by default.

However, you can easily override this option by updating the config file, `od_config.py`, in the toolbox's root directory.  Just open that file in a code or text editor, find where it says `"lineShapeType": arcpy.nax.LineShapeType.NoLine,` and change it to "lineShapeType": arcpy.nax.LineShapeType.StraightLine,`.  You'll need to close and reopen Pro (if it was open) or the toolbox won't pick up the changes to this file (it gets cached).

I see now that this information isn't clearly explained in the documentation, so I'll update that.  Sorry for your confusion!

**Comment by croemer1** [comment]
Hi Melinda,
everything is fine now.
Thanks for your quick response, I thought Feature Class is just used when someone want the shapes, but I could have find out myself, I checked the code in solve_large_odcm but not od_config.
